### ISSUE TITLE
Fails to launch on macOS Mojave, NullPointerException

### ISSUE THREAD

**Issue by andyhunt** [eclab/edisyn#30]
Double-clicking or right-clicking to open app produces no results. Running the executable from the shell produces the following (hopefully helpful?) stack trace:

/Applications/Edisyn.app/Contents/MacOS$ Edisyn
java.lang.NullPointerException
	at sun.font.FontDesignMetrics.getDefaultFrc(FontDesignMetrics.java:157)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:278)
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1113)
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
	at javax.swing.plaf.basic.BasicGraphicsUtils.getPreferredButtonSize(BasicGraphicsUtils.java:276)
	at com.apple.laf.AquaButtonUI.getPreferredSize(AquaButtonUI.java:443)
	at com.apple.laf.AquaButtonUI.getMinimumSize(AquaButtonUI.java:431)
	at javax.swing.JComponent.getMinimumSize(JComponent.java:1744)
	at javax.swing.plaf.basic.BasicOptionPaneUI.addButtonComponents(BasicOptionPaneUI.java:693)
	at javax.swing.plaf.basic.BasicOptionPaneUI.createButtonArea(BasicOptionPaneUI.java:630)
	at com.apple.laf.AquaOptionPaneUI.createButtonArea(AquaOptionPaneUI.java:53)
	at javax.swing.plaf.basic.BasicOptionPaneUI.installComponents(BasicOptionPaneUI.java:178)
	at javax.swing.plaf.basic.BasicOptionPaneUI.installUI(BasicOptionPaneUI.java:141)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JOptionPane.setUI(JOptionPane.java:1860)
	at javax.swing.JOptionPane.updateUI(JOptionPane.java:1882)
	at javax.swing.JOptionPane.<init>(JOptionPane.java:1845)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:857)
	at edisyn.Synth.showMultiOption(Synth.java:2612)
	at edisyn.Synth.showMultiOption(Synth.java:2624)
	at edisyn.gui.Favorites.doNewSynthDialog(Favorites.java:170)
	at edisyn.Synth.doNewSynthPanel(Synth.java:6843)
	at edisyn.Edisyn.main(Edisyn.java:42)
Exception in thread "main" java.lang.NullPointerException
	at sun.font.FontDesignMetrics.getDefaultFrc(FontDesignMetrics.java:157)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:278)
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1113)
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
	at javax.swing.plaf.basic.BasicGraphicsUtils.getPreferredButtonSize(BasicGraphicsUtils.java:276)
	at com.apple.laf.AquaButtonUI.getPreferredSize(AquaButtonUI.java:443)
	at com.apple.laf.AquaButtonUI.getMinimumSize(AquaButtonUI.java:431)
	at javax.swing.JComponent.getMinimumSize(JComponent.java:1744)
	at javax.swing.plaf.basic.BasicOptionPaneUI.addButtonComponents(BasicOptionPaneUI.java:693)
	at javax.swing.plaf.basic.BasicOptionPaneUI.createButtonArea(BasicOptionPaneUI.java:630)
	at com.apple.laf.AquaOptionPaneUI.createButtonArea(AquaOptionPaneUI.java:53)
	at javax.swing.plaf.basic.BasicOptionPaneUI.installComponents(BasicOptionPaneUI.java:178)
	at javax.swing.plaf.basic.BasicOptionPaneUI.installUI(BasicOptionPaneUI.java:141)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JOptionPane.setUI(JOptionPane.java:1860)
	at javax.swing.JOptionPane.updateUI(JOptionPane.java:1882)
	at javax.swing.JOptionPane.<init>(JOptionPane.java:1845)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:857)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637)
	at edisyn.Synth.doNewSynthPanel(Synth.java:6848)
	at edisyn.Edisyn.main(Edisyn.java:42)
2021-01-09 11:35:07.057 Edisyn[50173:5522592] Edisyn:Failed to launch JVM

**Comment by eclab** [comment]
This is definitely not an Edisyn error, it's a low-level Java error, where Java can't find a default font.  And it's very early in Edisyn's launch, before Edisyn has customized anything at all.  Some googling suggests this error shows up a lot in out of date versions of Java.  First, try updating to a more recent version of Java.  Next, my only remaining guess might be an (innocuous) line in Edisyn.java which sets the default UI manager; that line helps windows versions of the code use the default Windows look and feel; we could try removing that, but beyond that, you've got me.

**Comment by eclab** [comment]
I have just double-checked on Mojave, and Edisyn is working well there.  I don't have a good answer for what your problem might be at this point.

**Comment by eclab** [comment]
Any more feedback on this?  Would like to get you up and running but it seems to work just fine on my fresh copy of Mojave.

**Comment by andyhunt** [comment]
I did a Java security update, and lo and behold it works now. Some 
component must have been out of date and not updated correctly from 
HighSierra to Mojave. Seems to work now, thanks so much for checking in.

**Comment by eclab** [comment]
No problem, good to hear it wasn't an Edisyn issue.
