### ISSUE TITLE
impossible to connect to a Waldorf Pulse 2

### ISSUE THREAD

**Issue by jphaenlin** [eclab/edisyn#52]
Hi,
When trying to connect I get the message "an error occured while creating the synth editor for WaldorfPulse2" 
and there is the following trace on the terminal :

`java -jar ./edisyn.jaravax.sound.midi.MidiUnavailableException: Device or resource busy
	at java.desktop/com.sun.media.sound.MidiOutDevice.nOpen(Native Method)
	at java.desktop/com.sun.media.sound.MidiOutDevice.implOpen(MidiOutDevice.java:51)
	at java.desktop/com.sun.media.sound.AbstractMidiDevice.doOpen(AbstractMidiDevice.java:150)
	at java.desktop/com.sun.media.sound.AbstractMidiDevice.open(AbstractMidiDevice.java:117)
	at edisyn.Midi$MidiDeviceWrapper.getReceiver(Midi.java:149)
	at edisyn.Midi.getNewTuple(Midi.java:554)
	at edisyn.Synth.setupMIDI(Synth.java:1726)
	at edisyn.Synth.instantiate(Synth.java:349)
	at edisyn.Synth.instantiate(Synth.java:299)
	at edisyn.Edisyn.main(Edisyn.java:48)
WARNING: error with stack trace requested but there's no Throwable
java.lang.NullPointerException
	at edisyn.Synth.handleException(Synth.java:8934)
	at edisyn.Synth.showErrorWithStackTrace(Synth.java:2702)
	at edisyn.Synth.showErrorWithStackTrace(Synth.java:2729)
	at edisyn.Midi.getNewTuple(Midi.java:557)
	at edisyn.Synth.setupMIDI(Synth.java:1726)
	at edisyn.Synth.instantiate(Synth.java:349)
	at edisyn.Synth.instantiate(Synth.java:299)
	at edisyn.Edisyn.main(Edisyn.java:48)`

**Comment by SeanLuke** [comment]
This is usually caused by a bad MIDI device, a malformed driver of some sort, etc.  What OS are you running on?

**Comment by jphaenlin** [comment]
Linux, Fedora 35. Other programs are ok, for example jsynthlib.

**Comment by SeanLuke** [comment]
I can't speak to jsynthlib (and frankly that is surprising), but we had the same problem in Linux in issue #33.  The problem appeared to be Jack conflicting with the standard Java drivers.  Any chance this could be the same?

**Comment by SeanLuke** [comment]
Well, we still have to figure out how to deal with Jack.  :-(
