### ISSUE TITLE
Fedora run error "Can't Load Library: .. libawt_xawt.so

### ISSUE THREAD

**Issue by armelvil** [eclab/edisyn#71]
Running

java -jar edisyn.jar

On Fedora results in;

`Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-17.0.8.0.7-1.fc38.x86_64/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1392)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1390)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1389)
	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1427)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1401)
	at java.desktop/java.awt.Color.<clinit>(Color.java:277)
	at edisyn.gui.Style.<clinit>(Style.java:28)
	at edisyn.Edisyn.main(Edisyn.java:29)
`

Fix is to:

`dnf install java-17-openjdk-portable-static-libs.x86_64 java-17-openjdk-static-libs.x86_64`

Most likely do not need both, but noting this here in the event anyone else runs into this issue.

**Comment by eclab** [comment]
Wow that is a bad openjdk error.  On Line 28 of Edisyn's Style.java it just says innocently:

        public final static Color DEFAULT_BACKGROUND_COLOR = new Color(35, 35, 35);

... so creating a Color causes Java 17 to bomb?  Not a good sign, Fedora
